VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_spi
WS2812_DRIVER = vendor
WS2812_DRIVER_REQUIRED = yes

